In [5]:
import numpy as np
a2= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a2.max(axis=0)


array([[ 7,  8,  9],
       [10, 11, 12]])

In [10]:
a2.max(axis=1)

array([[ 4,  5,  6],
       [10, 11, 12]])

In [11]:
a2.max(axis=2)

array([[ 3,  6],
       [ 9, 12]])

In [12]:
np.sum(a2,axis=0)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [13]:
np.sum(a2,axis=1)

array([[ 5,  7,  9],
       [17, 19, 21]])

In [15]:
np.sum(a2,axis=2)

array([[ 6, 15],
       [24, 33]])

In [16]:
np.mean(a2)

6.5

In [17]:
np.sqrt(a2)

array([[[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[2.64575131, 2.82842712, 3.        ],
        [3.16227766, 3.31662479, 3.46410162]]])

In [18]:
np.std(a2)

3.452052529534663

In [41]:
a=np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [48]:
a1=np.split(a,2,axis=1)
a1

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [47]:
a2=np.split(np.array(a1),2)
a2

[array([[[ 1],
         [ 5],
         [ 9],
         [13]],
 
        [[ 2],
         [ 6],
         [10],
         [14]]]),
 array([[[ 3],
         [ 7],
         [11],
         [15]],
 
        [[ 4],
         [ 8],
         [12],
         [16]]])]

In [51]:
b=np.arange(17,33).reshape(2,4,2)
b

array([[[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]],

       [[25, 26],
        [27, 28],
        [29, 30],
        [31, 32]]])

In [33]:
np.concatenate((a,b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 3

In [28]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])